INSERT INTO bookstore.`book` (`name`, `author`, `description`, `language`, `year`, `price`, `stock`)
VALUES
('The Great Gatsby', 'F. Scott Fitzgerald', 'A classic novel about the American Dream', 'en', '1925', 19.99, 50),
('To Kill a Mockingbird', 'Harper Lee', 'A story of racial injustice in the American South', 'en', '1960', 15.99, 30),
('1984', 'George Orwell', 'A dystopian novel about totalitarianism', 'en', '1949', 24.99, 40),
('Pride and Prejudice', 'Jane Austen', 'A romantic novel about societal expectations', 'en', '1813', 12.99, 20),
('The Hobbit', 'J.R.R. Tolkien', 'A fantasy adventure novel', 'en', '1937', 29.99, 25),
('Harry Potter and the Sorcerer\'s Stone', 'J.K. Rowling', 'The first book in the Harry Potter series', 'en', '1997', 18.99, 60),
('The Catcher in the Rye', 'J.D. Salinger', 'A novel about teenage angst and rebellion', 'en', '1951', 17.99, 35),
('Moby-Dick', 'Herman Melville', 'A tale of the captains obsessive quest for the white whale', 'en', '1851', 22.99, 15),
('The Lord of the Rings', 'J.R.R. Tolkien', 'An epic fantasy trilogy', 'en', '1954', 39.99, 55),
('The Da Vinci Code', 'Dan Brown', 'A mystery-thriller novel', 'en', '2003', 26.99, 48),
('The Alchemist', 'Paulo Coelho', 'A philosophical novel about following ones dreams', 'en', '1988', 21.99, 42),
('Brave New World', 'Aldous Huxley', 'A dystopian novel about a futuristic society', 'en', '1932', 28.99, 38),
('Frankenstein', 'Mary Shelley', 'A classic Gothic novel about science and morality', 'en', '1818', 14.99, 27),
('The Odyssey', 'Homer', 'An ancient Greek epic poem', 'en', '1999', 19.99, 23),
('The Shining', 'Stephen King', 'A horror novel about a haunted hotel', 'en', '1977', 31.99, 29),
('The Hunger Games', 'Suzanne Collins', 'A dystopian novel set in a post-apocalyptic world', 'en', '2008', 16.99, 33),
('A Tale of Two Cities', 'Charles Dickens', 'A historical novel set during the French Revolution', 'en', '1859', 23.99, 36),
('The Road', 'Cormac McCarthy', 'A post-apocalyptic novel about a father and sons journey', 'en', '2006', 25.99, 44),
('One Hundred Years of Solitude', 'Gabriel García Márquez', 'A magical realist novel about the Buendía family', 'en', '1967', 27.99, 50),
('The Hitchhiker\'s Guide to the Galaxy', 'Douglas Adams', 'A comedic science fiction series', 'en', '1979', 20.99, 22),
('Wuthering Heights', 'Emily Brontë', 'A dark and passionate tale of love and revenge', 'en', '1847', 18.99, 28),
('The Girl with the Dragon Tattoo', 'Stieg Larsson', 'A psychological thriller novel', 'en', '2005', 29.99, 47),
('The Art of War', 'Sun Tzu', 'An ancient Chinese military treatise', 'en', '2005', 12.99, 18),
('The Count of Monte Cristo', 'Alexandre Dumas', 'An adventure novel about revenge and redemption', 'en', '1844', 34.99, 31),
('The Picture of Dorian Gray', 'Oscar Wilde', 'A philosophical novel about the consequences of indulgence', 'en', '1890', 16.99, 39),
('The Kite Runner', 'Khaled Hosseini', 'A novel about friendship, betrayal, and redemption', 'en', '2003', 21.99, 26),
('The Grapes of Wrath', 'John Steinbeck', 'A novel about the struggles of the Joad family during the Great Depression', 'en', '1939', 24.99, 34),
('Crime and Punishment', 'Fyodor Dostoevsky', 'A psychological novel about morality and redemption', 'en', '1866', 28.99, 37),
('The Brothers Karamazov', 'Fyodor Dostoevsky', 'A philosophical novel about family and morality', 'en', '1880', 30.99, 45),
('The Scarlet Letter', 'Nathaniel Hawthorne', 'A novel about sin, guilt, and redemption in Puritan society', 'en', '1850', 19.99, 24),
('The Sun Also Rises', 'Ernest Hemingway', 'A novel about the "Lost Generation" after World War I', 'en', '1926', 22.99, 32),
('Gone with the Wind', 'Margaret Mitchell', 'A historical novel set during the American Civil War', 'en', '1936', 26.99, 49),
('The Wind in the Willows', 'Kenneth Grahame', 'A classic children\'s novel about animal adventures', 'en', '1908', 14.99, 21),
('The Silence of the Lambs', 'Thomas Harris', 'A psychological horror novel featuring Hannibal Lecter', 'en', '1988', 32.99, 41);
